## Data Cleaning am Beispiel der Datenjagd

In [15]:
# pandas library für data manipulation & analysis importieren
import pandas as pd

In [16]:
datenjagd =pd.read_csv("Daten/Datenjagd.csv")
datenjagd

,Antwort Nr.,Schuhart,Anzahl Stifte im Etui,"Sitzplatzdistanz zur Wandtafel (Meter, geschätzt oder gemessen)",Anzahl Gegenstände auf dem Tisch,Hunger,Subjektive Temeratureinschätzung,Anzahl Schlüssel am Schlüsselbund,Lieblingsgetraenk in der Pause,Distanz zur nächsten Wand geschätzt (Meter),...,Einschlafzeit gestern Abend,Zeitdauer für 10 Hampelmänner (Sekunden),Handyhülle vorhanden?,Aufstehzeit heute Morgen,Geschätzte Temperatur im Raum (Grad Celsius),Stresslevel,Breite des Handys (gemessen in mm),Aufstehzeit am Wochenende,Anzahl Apps auf dem Handy,Länge des eigenen Füllers/Stiftes (cm)
0,1,Sportschuhe,5.0,8.0,5,2.000000,neutral,4,Wasser,0.10,...,10min,8.0,Ja,7:20,20.0,3.0,78.0,9.000000e+00,20.0,14.0
1,2,Sneaker,16.0,NaN,4,2.000000,neutral,2,Eistee,2.00,...,6min,NaN,Ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Sneaker,7.0,6.0,7,5.000000,neutral,2,Mate,1.00,...,4s,5.0,Ja,6:30,27.0,2.0,NaN,NaN,NaN,NaN
3,4,Sneaker,NaN,6.5,5,1.000000,neutral,6,Kaffee,0.50,...,NaN,NaN,Ja,NaN,24.0,2.0,64.0,NaN,89.0,NaN
4,5,Andere,17.0,6.7,5,2.300000,neutral,4,Wasser,1.00,...,10 min,10.0,Ja,5 sek,25.0,1.5,67.0,1.000000e+01,inf,10.0
5,6,Sneaker,13.0,6.0,3,2.000000,warm,2,Wasser,1.50,...,5,NaN,Ja,7,24.0,3.0,50.0,8.000000e+00,80.0,12.0
6,7,Sneaker,38.0,7.0,2,NaN,neutral,2,NaN,2.00,...,NaN,NaN,Ja,Viertel nach sieben,20.0,3.0,71.5,NaN,20.0,10.0
7,8,Sneaker,25.0,6.5,6,3.000000,warm,3,Mate,0.30,...,00:30 Uhr,6.0,Ja,07:15,23.0,3.0,74.0,1.130000e+01,224.0,7.0
8,9,Andere,3.0,7.5,5,1.982828,neutral,1,Eistee,1.00,...,23:45,10.0,Ja,6:30,23.0,4.0,8.0,9.000000e+00,40.0,10.0
9,10,Sneaker,13.0,6.8,2,2.000000,neutral,3,Wasser,1.00,...,2 Minuten,9.0,Ja,2 Minuten,19.0,2.0,7.1,9.000000e+00,51.0,12.5
10,11,Sneaker,31.0,6.0,5,2.000000,neutral,2,Wasser,1.50,...,23:11,10.0,Ja,08:20,22.0,2.0,8.5,9.000000e+00,97.0,14.5
11,12,Sneaker,20.0,7.0,7,5.000000,neutral,1,Wasser,0.00,...,11:50,5.0,NaN,6:56,24.0,2.0,7.4,1.150000e+01,NaN,NaN
12,13,Sneaker,53.0,6.5,4,3.000000,neutral,2,Eistee,2.60,...,11:30,12.0,Ja,07:03,22.0,3.0,7.4,7.300000e+00,208.0,14.6
13,14,Sneaker,22.0,7.0,7,2.000000,neutral,0,Cola,1.00,...,4,NaN,Ja,2,19.0,2.0,71.0,9.000000e+00,109.0,NaN
14,15,Sneaker,42.0,6.7,5,1.000000,neutral,2,Wasser,1.67,...,drei Jahre,16.7,Ja,30 min,22.0,5.0,67.0,1.000000e+58,292.0,15.0

Bevor Daten analysiert werden, sollten Variablen nach ihrer Bedeutung und Messart gruppiert werden. Nicht jede Zahl beschreibt dieselbe Art von Information. Deshalb braucht es ein Verständnis der Variablentypen.

*Namenskonventionen im Datensatz*

* _time_s → **Zeitdauer** (Messung in Sekunden)
  Beispiele: Reaktionszeit, Bewegungsdauer, Aktivitätsdauer

* _time → **Zeitpunkt** (Uhrzeit)
  Beispiele: Einschlafzeit, Aufstehzeit

* _level → **Subjektive Skala** (Selbsteinschätzung)
  Beispiele: Stresslevel, Hungerlevel, Konzentration

* _count → **Diskrete Zählwerte**
  Beispiele: Anzahl Schritte, Tabs, Apps

* \_estimated_ → **Geschätzte Werte**
  Beispiele: geschätzte Distanz oder Temperatur

In [17]:
datenjagd.columns = [
    "id",
    "shoe_type",
    "pen_count",
    "seat_distance_board_m",
    "items_on_desk_count",
    "hunger_level",
    "temperature_feeling_level",
    "key_count",
    "favorite_break_drink",
    "wall_distance_estimated_m",
    "favorite_season",
    "seat_satisfaction_level",
    "concentration_level",
    "door_walk_time_s",
    "corridor_round_steps",
    "fatigue_level",
    "current_mood",
    "count_1_to_20_time_s",
    "middle_name_letter_count",
    "chair_height_estimated_cm",
    "favorite_subject",
    "did_eat_breakfast",
    "transport_wheel_count",
    "browser_tab_count",
    "first_name_write_time_s",
    "desk_height_mm",
    "sleep_time",
    "jumping_jacks_10_time_s",
    "has_phone_case",
    "wake_time_today",
    "room_temperature_estimated_c",
    "stress_level",
    "phone_width_mm",
    "wake_time_weekend",
    "app_count_phone",
    "pen_length_cm"
]
datenjagd.drop(columns=["id"], inplace=True)

In [18]:
datenpunkte_vorher = datenjagd.shape[0]
datenjagd.drop_duplicates(inplace=True)
datenpunkte_nachher = datenjagd.shape[0]    
print(f"Anzahl der Duplikate: {datenpunkte_vorher-datenpunkte_nachher}")

Anzahl der Duplikate: 0

In [19]:
datenjagd.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   shoe_type                     15 non-null     str
 1   pen_count                     14 non-null     float64
 2   seat_distance_board_m         14 non-null     float64
 3   items_on_desk_count           15 non-null     int64
 4   hunger_level                  14 non-null     float64
 5   temperature_feeling_level     15 non-null     str
 6   key_count                     15 non-null     int64
 7   favorite_break_drink          14 non-null     str
 8   wall_distance_estimated_m     15 non-null     float64
 9   favorite_season               15 non-null     str
 10  seat_satisfaction_level       15 non-null     int64
 11  concentration_level           15 non-null     float64
 12  door_walk_time_s              14 non-null     str
 13  corridor_round_steps          10 non-null     float64
 14  fatigue_level                 15 non-null     int64
 15  current_mood                  15 non-null     str
 16  count_1_to_20_time_s          15 non-null     str
 17  middle_name_letter_count      15 non-null     str
 18  chair_height_estimated_cm     13 non-null     float64
 19  favorite_subject              15 non-null     str
 20  did_eat_breakfast             14 non-null     str
 21  transport_wheel_count         15 non-null     int64
 22  browser_tab_count             15 non-null     int64
 23  first_name_write_time_s       15 non-null     float64
 24  desk_height_mm                13 non-null     float64
 25  sleep_time                    13 non-null     str
 26  jumping_jacks_10_time_s       10 non-null     float64
 27  has_phone_case                14 non-null     str
 28  wake_time_today               13 non-null     str
 29  room_temperature_estimated_c  14 non-null     float64
 30  stress_level                  14 non-null     float64
 31  phone_width_mm                13 non-null     float64
 32  wake_time_weekend             11 non-null     float64
 33  app_count_phone               12 non-null     float64
 34  pen_length_cm                 10 non-null     float64
dtypes: float64(16), int64(6), str(13)
memory usage: 4.2 KB

In [20]:
datenjagd

,shoe_type,pen_count,seat_distance_board_m,items_on_desk_count,hunger_level,temperature_feeling_level,key_count,favorite_break_drink,wall_distance_estimated_m,favorite_season,...,sleep_time,jumping_jacks_10_time_s,has_phone_case,wake_time_today,room_temperature_estimated_c,stress_level,phone_width_mm,wake_time_weekend,app_count_phone,pen_length_cm
0,Sportschuhe,5.0,8.0,5,2.000000,neutral,4,Wasser,0.10,Sommer,...,10min,8.0,Ja,7:20,20.0,3.0,78.0,9.000000e+00,20.0,14.0
1,Sneaker,16.0,NaN,4,2.000000,neutral,2,Eistee,2.00,Winter,...,6min,NaN,Ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sneaker,7.0,6.0,7,5.000000,neutral,2,Mate,1.00,Frühling,...,4s,5.0,Ja,6:30,27.0,2.0,NaN,NaN,NaN,NaN
3,Sneaker,NaN,6.5,5,1.000000,neutral,6,Kaffee,0.50,Sommer,...,NaN,NaN,Ja,NaN,24.0,2.0,64.0,NaN,89.0,NaN
4,Andere,17.0,6.7,5,2.300000,neutral,4,Wasser,1.00,Sommer,...,10 min,10.0,Ja,5 sek,25.0,1.5,67.0,1.000000e+01,inf,10.0
5,Sneaker,13.0,6.0,3,2.000000,warm,2,Wasser,1.50,Sommer,...,5,NaN,Ja,7,24.0,3.0,50.0,8.000000e+00,80.0,12.0
6,Sneaker,38.0,7.0,2,NaN,neutral,2,NaN,2.00,Frühling,...,NaN,NaN,Ja,Viertel nach sieben,20.0,3.0,71.5,NaN,20.0,10.0
7,Sneaker,25.0,6.5,6,3.000000,warm,3,Mate,0.30,Sommer,...,00:30 Uhr,6.0,Ja,07:15,23.0,3.0,74.0,1.130000e+01,224.0,7.0
8,Andere,3.0,7.5,5,1.982828,neutral,1,Eistee,1.00,Sommer,...,23:45,10.0,Ja,6:30,23.0,4.0,8.0,9.000000e+00,40.0,10.0
9,Sneaker,13.0,6.8,2,2.000000,neutral,3,Wasser,1.00,Frühling,...,2 Minuten,9.0,Ja,2 Minuten,19.0,2.0,7.1,9.000000e+00,51.0,12.5
10,Sneaker,31.0,6.0,5,2.000000,neutral,2,Wasser,1.50,Sommer,...,23:11,10.0,Ja,08:20,22.0,2.0,8.5,9.000000e+00,97.0,14.5
11,Sneaker,20.0,7.0,7,5.000000,neutral,1,Wasser,0.00,Winter,...,11:50,5.0,NaN,6:56,24.0,2.0,7.4,1.150000e+01,NaN,NaN
12,Sneaker,53.0,6.5,4,3.000000,neutral,2,Eistee,2.60,Frühling,...,11:30,12.0,Ja,07:03,22.0,3.0,7.4,7.300000e+00,208.0,14.6
13,Sneaker,22.0,7.0,7,2.000000,neutral,0,Cola,1.00,Frühling,...,4,NaN,Ja,2,19.0,2.0,71.0,9.000000e+00,109.0,NaN
14,Sneaker,42.0,6.7,5,1.000000,neutral,2,Wasser,1.67,Frühling,...,drei Jahre,16.7,Ja,30 min,22.0,5.0,67.0,1.000000e+58,292.0,15.0

Die folgende Aufteilung dient dazu, die Spalten später unterschiedlich zu verarbeiten:

- kategoriale Variablen kodieren,
- binäre Variablen speziell behandeln,
- ordinale Werte in einer Reihenfolge berücksichtigen,
- Zeitvariablen als Zeitdaten zu interpretieren,
- numerische Werte normalisieren oder analysieren.

Damit wird die Datenvorbereitung strukturierter und übersichtlicher.

In [21]:
categorical_cols = [
    "shoe_type",
    "favorite_break_drink",
    "favorite_season",
    "favorite_subject",
    "current_mood",
    "temperature_feeling_level"
]

binary_cols = [
    "did_eat_breakfast",
    "has_phone_case"
]

ordinal_cols = [
    "hunger_level",
    "seat_satisfaction_level",
    "concentration_level",
    "fatigue_level",
    "stress_level"
]

time_cols = [
    "sleep_time",
    "wake_time_today",
    "wake_time_weekend"
]

numeric_cols = [
    "pen_count",
    "seat_distance_board_m",
    "items_on_desk_count",
    "key_count",
    "wall_distance_estimated_m",
    "door_walk_time_s",
    "corridor_round_steps",
    "count_1_to_20_time_s",
    "middle_name_letter_count",
    "chair_height_estimated_cm",
    "transport_wheel_count",
    "browser_tab_count",
    "first_name_write_time_s",
    "desk_height_mm",
    "jumping_jacks_10_time_s",
    "room_temperature_estimated_c",
    "phone_width_mm",
    "app_count_phone",
    "pen_length_cm"
]

mapping = {
    "ja": True,
    "nein": False,
    "yes": True,
    "no": False,
    "true": True,
    "false": False
}

In [22]:
# Konvertieren der Datentypen
datenjagd[categorical_cols] = datenjagd[categorical_cols].astype("category") # Konvertieren der kategorischen Spalten
for col in binary_cols: # Konvertieren der binären Spalten
    datenjagd[col] = (
    datenjagd[col]
      .astype(str)
      .str.strip()
      .str.lower()
      .map(mapping)
)
datenjagd[ordinal_cols] = datenjagd[ordinal_cols].astype("float64") # Konvertieren der ordinalen Spalten in numerische Werte
datenjagd[numeric_cols] = datenjagd[numeric_cols].apply(pd.to_numeric, errors="coerce")

In [23]:
for col in categorical_cols:
    print(f"{datenjagd[col].value_counts(dropna=False)}\n")

shoe_type
Sneaker        12
Andere          2
Sportschuhe     1
Name: count, dtype: int64

favorite_break_drink
Wasser    7
Eistee    3
Mate      2
Cola      1
Kaffee    1
NaN       1
Name: count, dtype: int64

favorite_season
Sommer      7
Frühling    6
Winter      2
Name: count, dtype: int64

favorite_subject
Informatik     4
ein anderes    4
Englisch       2
Mathe          2
Musik          2
Sport          1
Name: count, dtype: int64

current_mood
anders          4
gut             4
interessiert    3
neugierig       3
überfordert     1
Name: count, dtype: int64

temperature_feeling_level
neutral    13
warm        2
Name: count, dtype: int64

In [24]:
datenjagd

,shoe_type,pen_count,seat_distance_board_m,items_on_desk_count,hunger_level,temperature_feeling_level,key_count,favorite_break_drink,wall_distance_estimated_m,favorite_season,...,sleep_time,jumping_jacks_10_time_s,has_phone_case,wake_time_today,room_temperature_estimated_c,stress_level,phone_width_mm,wake_time_weekend,app_count_phone,pen_length_cm
0,Sportschuhe,5.0,8.0,5,2.000000,neutral,4,Wasser,0.10,Sommer,...,10min,8.0,True,7:20,20.0,3.0,78.0,9.000000e+00,20.0,14.0
1,Sneaker,16.0,NaN,4,2.000000,neutral,2,Eistee,2.00,Winter,...,6min,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sneaker,7.0,6.0,7,5.000000,neutral,2,Mate,1.00,Frühling,...,4s,5.0,True,6:30,27.0,2.0,NaN,NaN,NaN,NaN
3,Sneaker,NaN,6.5,5,1.000000,neutral,6,Kaffee,0.50,Sommer,...,NaN,NaN,True,NaN,24.0,2.0,64.0,NaN,89.0,NaN
4,Andere,17.0,6.7,5,2.300000,neutral,4,Wasser,1.00,Sommer,...,10 min,10.0,True,5 sek,25.0,1.5,67.0,1.000000e+01,inf,10.0
5,Sneaker,13.0,6.0,3,2.000000,warm,2,Wasser,1.50,Sommer,...,5,NaN,True,7,24.0,3.0,50.0,8.000000e+00,80.0,12.0
6,Sneaker,38.0,7.0,2,NaN,neutral,2,NaN,2.00,Frühling,...,NaN,NaN,True,Viertel nach sieben,20.0,3.0,71.5,NaN,20.0,10.0
7,Sneaker,25.0,6.5,6,3.000000,warm,3,Mate,0.30,Sommer,...,00:30 Uhr,6.0,True,07:15,23.0,3.0,74.0,1.130000e+01,224.0,7.0
8,Andere,3.0,7.5,5,1.982828,neutral,1,Eistee,1.00,Sommer,...,23:45,10.0,True,6:30,23.0,4.0,8.0,9.000000e+00,40.0,10.0
9,Sneaker,13.0,6.8,2,2.000000,neutral,3,Wasser,1.00,Frühling,...,2 Minuten,9.0,True,2 Minuten,19.0,2.0,7.1,9.000000e+00,51.0,12.5
10,Sneaker,31.0,6.0,5,2.000000,neutral,2,Wasser,1.50,Sommer,...,23:11,10.0,True,08:20,22.0,2.0,8.5,9.000000e+00,97.0,14.5
11,Sneaker,20.0,7.0,7,5.000000,neutral,1,Wasser,0.00,Winter,...,11:50,5.0,NaN,6:56,24.0,2.0,7.4,1.150000e+01,NaN,NaN
12,Sneaker,53.0,6.5,4,3.000000,neutral,2,Eistee,2.60,Frühling,...,11:30,12.0,True,07:03,22.0,3.0,7.4,7.300000e+00,208.0,14.6
13,Sneaker,22.0,7.0,7,2.000000,neutral,0,Cola,1.00,Frühling,...,4,NaN,True,2,19.0,2.0,71.0,9.000000e+00,109.0,NaN
14,Sneaker,42.0,6.7,5,1.000000,neutral,2,Wasser,1.67,Frühling,...,drei Jahre,16.7,True,30 min,22.0,5.0,67.0,1.000000e+58,292.0,15.0

### Zeitspalten — verstehen, bevor Transformationen durchgeführt werden

Bevor Zeitvariablen transformiert oder analysiert werden, muss zuerst geklärt werden, **welche Art von Zeitinformation** vorliegt.
Nicht jede Angabe, die wie eine Uhrzeit aussieht, bedeutet statistisch dasselbe.

**Es gibt zwei grundlegende Konzepte:**

**1. Zeitpunkte (Uhrzeiten)**
Beschreiben, *wann* etwas passiert ist.

Beispiele:

* sleep_time
* wake_time_today
* wake_time_weekend

Eigenschaften:

* Position auf einer täglichen Zeitachse
* Differenzen zwischen Zeitpunkten ergeben eine Dauer
* Mittelwerte von Uhrzeiten sind oft nicht sinnvoll

Typischer Fehler:
Der Durchschnitt von 23:30 und 01:30 ist **nicht** 12:30.


**2. Zeitdauern**

Beschreiben, *wie lange* etwas dauert.

Beispiele:

* door_walk_time_s
* jumping_jacks_10_time_s
* count_1_to_20_time_s

Eigenschaften:

* echte messbare Grössen
* Mittelwerte und Vergleiche sind sinnvoll
* direkt statistisch auswertbar

--- 

Diese Unterscheidung ist wichtig, weil falsche Ergebnisse entstehen können, wenn Uhrzeiten wie normale Zahlen behandelt werden:

* Zeitpunkte müssen zuerst sinnvoll umgerechnet werden
* Zeitdauern können direkt analysiert werden
* Visualisierungen verhalten sich unterschiedlich je nach Interpretation

Gute Datenanalyse beginnt mit dem Verständnis der Bedeutung einer Variable — nicht mit sofortiger Transformation.

In [25]:
times = datenjagd[time_cols]
times

    sleep_time      wake_time_today  wake_time_weekend
0        10min                 7:20       9.000000e+00
1         6min                  NaN                NaN
2           4s                 6:30                NaN
3          NaN                  NaN                NaN
4       10 min                5 sek       1.000000e+01
5            5                    7       8.000000e+00
6          NaN  Viertel nach sieben                NaN
7    00:30 Uhr                07:15       1.130000e+01
8        23:45                 6:30       9.000000e+00
9    2 Minuten            2 Minuten       9.000000e+00
10       23:11                08:20       9.000000e+00
11       11:50                 6:56       1.150000e+01
12       11:30                07:03       7.300000e+00
13           4                    2       9.000000e+00
14  drei Jahre               30 min       1.000000e+58

### Warum hier eine zusätzliche Funktion nötig ist
`pd.to_datetime` ist zu allgemein für diesen Datensatz. Er versucht viele Formate automatisch zu erkennen, kann aber nicht zuverlässig unterscheiden zwischen:

- echten Uhrzeiten (23:45, 07:15 Uhr, 11.3)
- Dauerangaben (10min, 4s, 2 Minuten)

**Die zusätzliche Funktion macht die Regeln explizit:**

- akzeptiert nur sinnvolle Uhrzeitformate
- wandelt Dezimalwerte wie 11.3 gezielt in 11:30 um
- verwirft Dauerangaben bewusst als NaT

Dadurch bleibt die Qualität der Zeitdaten erhalten und es wird keine falsche Zeitinformation erzeugt.
Weil wir nur die Tageszeit interessieren, gibt `parse_timepoint` ausserdem ein reines time-Objekt zurück statt ein vollständiges Datum.

In [26]:
import re
from datetime import time

# parse_timepoint wandelt verschiedene Uhrzeitformate in ein reines time-Objekt um.
# Datum wird verworfen, weil uns nur der Tageszeitpunkt interessiert.
def parse_timepoint(value):
    if pd.isna(value):
        return pd.NaT
    s = str(value).strip().lower()
    if not s:
        return pd.NaT
    # Entferne das Wort "Uhr" am Ende und normalisiere Leerzeichen
    s = re.sub(r"\s*uhr$", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    # Sonderfall: sprachliche Beschreibung "Viertel nach sieben"
    if s in ["viertel nach sieben", "viertel nach 7", "viertel nach 07"]:
        s = "07:15"
    # Standardformat HH:MM
    if re.match(r"^[0-2]?\d:[0-5]\d$", s):
        ts = pd.to_datetime(s, format="%H:%M", errors="coerce")
        return ts.time() if pd.notna(ts) else pd.NaT
    # Ganze Stunden wie 7 oder 9
    if re.match(r"^[0-2]?\d$", s):
        hour = int(s)
        if 0 <= hour <= 23:
            return time(hour=hour)
    # Dezimalformat wie 11.3, 11.5 oder 7.3
    if re.match(r"^[0-2]?\d\.(\d+)$", s):
        hour_str, frac = s.split(".", 1)
        hour = int(hour_str)
        minute = None
        if frac in ["0", "00"]:
            minute = 0
        elif frac in ["3", "30", "5", "50"]:
            minute = 30
        elif frac == "25":
            minute = 15
        elif frac == "75":
            minute = 45
        if minute is not None and 0 <= hour <= 23:
            return time(hour=hour, minute=minute)
    return pd.NaT

# sleep_time ist als Uhrzeit zu interpretieren, keine Dauer.
def parse_sleep_time(value):
    if pd.isna(value):
        return pd.NaT
    s = str(value).strip().lower()
    if not s:
        return pd.NaT
    if ":" in s or "uhr" in s:
        s = re.sub(r"\s*uhr$", "", s)
        ts = pd.to_datetime(s, format="%H:%M", errors="coerce")
        return ts.time() if pd.notna(ts) else pd.NaT
    # Dauerangaben wie 10min, 4s oder 2 Minuten sind keine Uhrzeiten
    return pd.NaT

datenjagd["sleep_time"] = datenjagd["sleep_time"].apply(parse_sleep_time)
datenjagd["wake_time_today"] = datenjagd["wake_time_today"].apply(parse_timepoint)
datenjagd["wake_time_weekend"] = datenjagd["wake_time_weekend"].apply(parse_timepoint)

In [27]:
datenjagd[time_cols]

   sleep_time wake_time_today wake_time_weekend
0         NaT        07:20:00          09:00:00
1         NaT             NaT               NaT
2         NaT        06:30:00               NaT
3         NaT             NaT               NaT
4         NaT             NaT          10:00:00
5         NaT        07:00:00          08:00:00
6         NaT        07:15:00               NaT
7    00:30:00        07:15:00          11:30:00
8    23:45:00        06:30:00          09:00:00
9         NaT             NaT          09:00:00
10   23:11:00        08:20:00          09:00:00
11   11:50:00        06:56:00          11:30:00
12   11:30:00        07:03:00          07:30:00
13        NaT        02:00:00          09:00:00
14        NaT             NaT               NaT

In [28]:
datenjagd.dtypes
datenjagd.isna().sum()

shoe_type                        0
pen_count                        1
seat_distance_board_m            1
items_on_desk_count              0
hunger_level                     1
temperature_feeling_level        0
key_count                        0
favorite_break_drink             1
wall_distance_estimated_m        0
favorite_season                  0
seat_satisfaction_level          0
concentration_level              0
door_walk_time_s                 2
corridor_round_steps             5
fatigue_level                    0
current_mood                     0
count_1_to_20_time_s             4
middle_name_letter_count         1
chair_height_estimated_cm        2
favorite_subject                 0
did_eat_breakfast                1
transport_wheel_count            0
browser_tab_count                0
first_name_write_time_s          0
desk_height_mm                   2
sleep_time                      10
jumping_jacks_10_time_s          5
has_phone_case                   1
wake_time_today                  5
room_temperature_estimated_c     1
stress_level                     1
phone_width_mm                   2
wake_time_weekend                5
app_count_phone                  3
pen_length_cm                    5
dtype: int64

### Umgang mit NaN-Werten und erste Datenprüfung

Fehlende Werte (`NaN`) sind ein normaler Bestandteil realer Datensätze.
Bevor Analysen durchgeführt werden, sollte bewusst entschieden werden, wie mit fehlenden Informationen umgegangen wird.

**Mögliche Strategien für NaN-Werte**

* Entfernen von Zeilen mit NaN-Werten: sinnvoll bei wenigen fehlenden Einträgen oder wenn vollständige Daten zwingend nötig sind
* Ersetzen durch statistische Kennwerte: z. B. Mittelwert oder Median bei numerischen Spalten
* Ersetzen durch spezielle Kategorien: z. B. `"Unbekannt"` oder `"Keine Angabe"` bei kategorialen Variablen

In [29]:
# Zeilen mit zu vielen NaN-Werten entfernen:
max_missing = 3
keep = datenjagd.isna().sum(axis=1) <= max_missing
datenjagd = datenjagd.loc[keep].copy()

# Typgerechte Imputation
for col in categorical_cols:
    datenjagd[col] = datenjagd[col].cat.add_categories("Unbekannt")
datenjagd[categorical_cols] = datenjagd[categorical_cols].fillna("Unbekannt")
datenjagd[binary_cols] = datenjagd[binary_cols].fillna(0)
datenjagd[ordinal_cols] = datenjagd[ordinal_cols].fillna(datenjagd[ordinal_cols].median())
datenjagd[numeric_cols] = datenjagd[numeric_cols].fillna(datenjagd[numeric_cols].median())

In [30]:
datenjagd

,shoe_type,pen_count,seat_distance_board_m,items_on_desk_count,hunger_level,temperature_feeling_level,key_count,favorite_break_drink,wall_distance_estimated_m,favorite_season,...,sleep_time,jumping_jacks_10_time_s,has_phone_case,wake_time_today,room_temperature_estimated_c,stress_level,phone_width_mm,wake_time_weekend,app_count_phone,pen_length_cm
0,Sportschuhe,5.0,8.0,5,2.000000,neutral,4,Wasser,0.1,Sommer,...,NaT,8.0,True,07:20:00,20.0,3.0,78.0,09:00:00,20.0,14.00
4,Andere,17.0,6.7,5,2.300000,neutral,4,Wasser,1.0,Sommer,...,NaT,10.0,True,NaT,25.0,1.5,67.0,10:00:00,inf,10.00
5,Sneaker,13.0,6.0,3,2.000000,warm,2,Wasser,1.5,Sommer,...,NaT,9.5,True,07:00:00,24.0,3.0,50.0,08:00:00,80.0,12.00
7,Sneaker,25.0,6.5,6,3.000000,warm,3,Mate,0.3,Sommer,...,00:30:00,6.0,True,07:15:00,23.0,3.0,74.0,11:30:00,224.0,7.00
8,Andere,3.0,7.5,5,1.982828,neutral,1,Eistee,1.0,Sommer,...,23:45:00,10.0,True,06:30:00,23.0,4.0,8.0,09:00:00,40.0,10.00
9,Sneaker,13.0,6.8,2,2.000000,neutral,3,Wasser,1.0,Frühling,...,NaT,9.0,True,NaT,19.0,2.0,7.1,09:00:00,51.0,12.50
10,Sneaker,31.0,6.0,5,2.000000,neutral,2,Wasser,1.5,Sommer,...,23:11:00,10.0,True,08:20:00,22.0,2.0,8.5,09:00:00,97.0,14.50
11,Sneaker,20.0,7.0,7,5.000000,neutral,1,Wasser,0.0,Winter,...,11:50:00,5.0,0,06:56:00,24.0,2.0,7.4,11:30:00,88.5,12.25
12,Sneaker,53.0,6.5,4,3.000000,neutral,2,Eistee,2.6,Frühling,...,11:30:00,12.0,True,07:03:00,22.0,3.0,7.4,07:30:00,208.0,14.60

### Weitere empfohlene Prüfschritte vor der Analyse

* Ausreisser untersuchen: ungewöhnlich grosse oder kleine Werte können Messfehler oder interessante Sonderfälle sein
* Korrelationen prüfen: zeigen mögliche Zusammenhänge zwischen numerischen Variablen
* Verteilungen analysieren: helfen zu verstehen, ob Daten symmetrisch, schief oder mehrgipflig verteilt sind

Datenanalyse beginnt nicht mit Modellen oder Diagrammen, sondern mit systematischer Datenprüfung.

In [31]:
datenjagd.to_csv("Daten/Datenjagd_clean.csv", index=False)